spring.application.name=tradingbot

# SMA Indicators
smaindicator.fast.barcount=20
smaindicator.slow.barcount=60

# RSI Indicator
rsiindicator.barcount=14
rsiindicator.value=80

# Alpaca
alpaca.api.key=PK5BUQWP5NXQ7BMU5CWBP4HJCJ
alpaca.api.secret=jE1qQd9CTzM6NXEUn4QPxPWbRbq4PbUYuAHeuBrgWSb

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/tradingbot
spring.data.mongodb.database=tradingbot

